local function Instn(cls,prop)local obj = Instance.new(cls)for i,v in pairs(prop)do obj[i] = v end return obj end
local Plr = game.Players.LocalPlayer
local GetM = Plr:GetMouse()
local ScreenGui = Instn("ScreenGui",{Name = '', Parent = Plr.PlayerGui, ResetOnSpawn = false})
local Title = Instn("Frame",{AnchorPoint = Vector2.new(.5,.5), BackgroundColor3 = Color3.new(1,1,1), BorderColor3 = Color3.new(0,0,0), Name = '',Parent = ScreenGui, Position = UDim2.new(.5,0,.5,0), Size = UDim2.new(0,175,0,110)})
local Drag = Instn("TextButton",{AutoButtonColor = false, BackgroundColor3 = Color3.new(1,1,1), BorderColor3 = Color3.new(0,0,0), Name = '',Parent = Title, Size = UDim2.new(0,150,0,25), Text = "Islands", TextColor = BrickColor.new(1003), TextScaled = true})
local Exit = Instn("TextButton",{BackgroundColor3 = Color3.new(1,1,1), BorderColor3 = Color3.new(0,0,0), Name = '',Parent = Title, Position = UDim2.new(0,150,0,0), Size = UDim2.new(0,25,0,25), Text = "X", TextColor = BrickColor.new(1003), TextScaled = true})
local Item1 = Instn("TextButton",{BackgroundColor3 = Color3.new(1,0,0), BorderColor3 = Color3.new(0,0,0), Name = '',Parent = Title, Position = UDim2.new(0,5,0,30), Size = UDim2.new(0,78,0,25), Text = "Snowman", TextColor = BrickColor.new(1003), TextScaled = true})
local Item2 = Instn("TextButton",{BackgroundColor3 = Color3.new(1,0,0), BorderColor3 = Color3.new(0,0,0), Name = '',Parent = Title, Position = UDim2.new(0,5,0,60), Size = UDim2.new(0,78,0,25), Text = " Item2", TextColor = BrickColor.new(1003), TextScaled = true})
local Item3 = Instn("TextButton",{BackgroundColor3 = Color3.new(1,0,0), BorderColor3 = Color3.new(0,0,0), Name = '',Parent = Title, Position = UDim2.new(0,88,0,30), Size = UDim2.new(0,78,0,25), Text = "Item3", TextColor = BrickColor.new(1003), TextScaled = true})
local Item4 = Instn("TextButton",{BackgroundColor3 = Color3.new(1,0,0), BorderColor3 = Color3.new(0,0,0), Name = '',Parent = Title, Position = UDim2.new(0,88,0,60), Size = UDim2.new(0,78,0,25), Text = "Item4", TextColor = BrickColor.new(1003), TextScaled = true})
local Dragg = false
local Toggli = false
Drag.MouseButton1Down:Connect(function()Dragg = true while Dragg do game.TweenService:Create(Title, TweenInfo.new(.1), {Position = UDim2.new(0,GetM.X,0,GetM.Y+35)}):Play()wait()end end)
Drag.MouseButton1Up:Connect(function()Dragg = false end)
Exit.MouseButton1Click:Connect(function()ScreenGui:Destroy()Toggli = false end)
Item1.MouseButton1Click:Connect(function()
	if Toggli then
		Toggli = false
		Item1.BackgroundColor3 = Color3.new(1,0,0)
	else
		Toggli = true
		Item1.BackgroundColor3 = Color3.new(0,1,0)
		while Toggli do

				wait()

local c = 0
game:GetService("RunService").RenderStepped:Connect(function()
    c = c + 1
    if c == 10 then c = 0
    local args = {
    [1] = {
        ["crit"] = true,
        ["hitUnit"] = game:GetService("Workspace").WildernessIsland.Entities:FindFirstChild("snowman")
    }
}
game:GetService("ReplicatedStorage").rbxts_include.node_modules.net.out._NetManaged.CLIENT_SWING_SWORD:InvokeServer(unpack(args))
end
end)
    wait(1)
while wait(4) do
        if game:GetService("Workspace").WildernessIsland.Entities:FindFirstChild("snowman") then
            game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(game:GetService("Workspace").WildernessIsland.Entities:FindFirstChild("snowman").HumanoidRootPart.Position + Vector3.new(0, -10, 0))
        end
end
wait(5)
for i = 1, math.huge do
    a()
end

Item2.MouseButton1Click:Connect(function()
	if Toggli then
		Toggli = false
		Item2.BackgroundColor3 = Color3.new(1,0,0)
	else
		Toggli = true
		Item2.BackgroundColor3 = Color3.new(0,1,0)
		while Toggli do

				wait()

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer,
    [2] = "f-10",
    [3] = "UseBlock",
    [4] = {
        ["cframe"] = CFrame.new(Vector3.new(-3979.0964355469, 2000.4998779297, -18.0029296875), Vector3.new(1, 4.3711388286738e-08, -8.7422776573476e-08))
    },
    [5] = workspace.Pets.Dolphin
}

game:GetService("ReplicatedStorage").API.DlsrioiDTNFHkBsFmFsUJHEAMOMA:InvokeServer(unpack(args))

			wait(40)
		end
	end
end)

Item3.MouseButton1Click:Connect(function()
	if Toggli then
		Toggli = false
		Item3.BackgroundColor3 = Color3.new(1,0,0)
	else
		Toggli = true
		Item3.BackgroundColor3 = Color3.new(0,1,0)
		while Toggli do

		   wait()

-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer,
    [2] = "f-5",
    [3] = "UseBlock",
    [4] = {
        ["cframe"] = CFrame.new(Vector3.new(-3985.5336914063, 2000.9451904297, -29.97216796875), Vector3.new(-1, -4.3711388286738e-08, 8.7422776573476e-08))
    },
    [5] = workspace.Pets.Dolphin
}

game:GetService("ReplicatedStorage").API.DlsrioiDTNFHkBsFmFsUJHEAMOMA:InvokeServer(unpack(args))

			wait(40)
		end
	end
end)

Item4.MouseButton1Click:Connect(function()
	if Toggli then
		Toggli = false
		Item4.BackgroundColor3 = Color3.new(1,0,0)
	else
		Toggli = true
		Item4.BackgroundColor3 = Color3.new(0,1,0)
		while Toggli do

local args = {
    [1] = game:GetService("Players").LocalPlayer,
    [2] = "f-11",
    [3] = "UseBlock3",
    [4] = {
        ["cframe"] = CFrame.new(Vector3.new(-3992.8898925781, 2003.2735595703, -26.791748046875), Vector3.new(-1, -4.3711388286738e-08, 8.7422776573476e-08))
    },
    [5] = workspace.Pets.Dolphin
}

game:GetService("ReplicatedStorage").API.DlsrioiDTNFHkBsFmFsUJHEAMOMA:InvokeServer(unpack(args))
			wait(40)
		end
	end
end)